spring:
  application:
    name: synergyflow
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

security:
  jwt:
    expected-audience: ${SECURITY_JWT_EXPECTED_AUDIENCE:synergyflow-api}
    clock-skew: ${SECURITY_JWT_CLOCK_SKEW:60}
  cors:
    allowed-origins: ${SECURITY_CORS_ALLOWED_ORIGINS:}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,modulith"
  endpoint:
    health:
      probes:
        enabled: true
