openapi: 3.1.0
info:
  title: SynergyFlow API - Knowledge Articles
  version: 1.0.0
paths:
  /articles:
    get:
      tags: [Knowledge]
      summary: List knowledge articles
      operationId: listArticles
      parameters:
        - $ref: '../modules/shared.yaml#/components/parameters/Page'
        - $ref: '../modules/shared.yaml#/components/parameters/Limit'
        - in: query
          name: q
          schema: { type: string, description: Full-text search query }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  page: { type: integer }
                  limit: { type: integer }
                  total: { type: integer }
                  items:
                    type: array
                    items: { $ref: '#/components/schemas/Article' }
        default: { $ref: '../modules/shared.yaml#/components/responses/ErrorResponse' }
    post:
      tags: [Knowledge]
      summary: Create article
      operationId: createArticle
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ArticleCreate' }
      responses:
        '201': { description: Created, content: { application/json: { schema: { $ref: '#/components/schemas/Article' } } } }
        default: { $ref: '../modules/shared.yaml#/components/responses/ErrorResponse' }

  /articles/{id}:
    get:
      tags: [Knowledge]
      summary: Get article
      operationId: getArticle
      parameters:
        - $ref: '../modules/shared.yaml#/components/parameters/IdPath'
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/Article' } } } }
        '404': { $ref: '../modules/shared.yaml#/components/responses/NotFound' }
        default: { $ref: '../modules/shared.yaml#/components/responses/ErrorResponse' }
    patch:
      tags: [Knowledge]
      summary: Update article
      operationId: updateArticle
      parameters:
        - $ref: '../modules/shared.yaml#/components/parameters/IdPath'
        - $ref: '../modules/shared.yaml#/components/parameters/IfMatch'
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ArticleUpdate' }
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/Article' } } } }
        default: { $ref: '../modules/shared.yaml#/components/responses/ErrorResponse' }

components:
  schemas:
    Article:
      type: object
      required: [id, title, status]
      properties:
        id: { type: string }
        title: { type: string }
        content: { type: string }
        category: { type: string, nullable: true }
        status: { $ref: '../modules/shared.yaml#/components/schemas/ArticleStatus' }
        ownerId: { type: string, nullable: true }
        expiresAt: { type: string, format: date-time, nullable: true }
        createdBy: { type: string }
        createdAt: { type: string, format: date-time }
    ArticleCreate:
      type: object
      required: [title, content, createdBy]
      properties:
        title: { type: string }
        content: { type: string }
        category: { type: string, nullable: true }
        ownerId: { type: string, nullable: true }
        expiresAt: { type: string, format: date-time, nullable: true }
        createdBy: { type: string }
    ArticleUpdate:
      type: object
      properties:
        title: { type: string }
        content: { type: string }
        category: { type: string, nullable: true }
        status: { $ref: '../modules/shared.yaml#/components/schemas/ArticleStatus' }
        ownerId: { type: string, nullable: true }
        expiresAt: { type: string, format: date-time, nullable: true }

