site_name: SynergyFlow ITSM PRD
# TODO: Update to actual repository URL
repo_url: https://example.com/synergyflow
docs_dir: docs
strict: true
theme:
  name: material
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc
  - pymdownx.superfences
plugins:
  - search
  - swagger-ui-tag
nav:
  - Home: index.md
  - Glossary: glossary.md
  - Contributing: contributing.md
  - Release Notes: release-notes.md
  - PRD:
    - Overview: prd/README.md
    - Executive Summary: prd/00-executive-summary.md
    - 1. User Experience Strategy: prd/01-user-experience-strategy.md
    - 2. ITIL v4 Core Features Specification: prd/02-itil-v4-core-features-specification.md
    - 3. System Architecture: prd/03-system-architecture-monolithic-approach.md
    - 4. Multi-Team Support & Intelligent Routing: prd/04-multi-team-support-intelligent-routing.md
    - 5. Integration Architecture: prd/05-integration-architecture.md
    - 6. Platform Administration: prd/06-platform-administration.md
    - 7. Notification System Design: prd/07-notification-system-design.md
    - 8. Reporting and Analytics Framework: prd/08-reporting-and-analytics-framework.md
    - 9. High Availability & Reliability Architecture: prd/09-high-availability-reliability-architecture.md
    - 10. Technology Stack Specifications: prd/10-technology-stack-specifications.md
    - 11. Testing Strategy (Spring Modulith): prd/11-testing-strategy-spring-modulith.md
    - 12. Enhanced Performance & Reliability Requirements: prd/12-enhanced-performance-reliability-requirements.md
    - 13. Security & Compliance Framework: prd/13-security-compliance-framework.md
    - 14. Updated Implementation Roadmap: prd/14-updated-implementation-roadmap-with-reliability-milestones.md
    - 15. Detailed Implementation Roadmap: prd/15-detailed-implementation-roadmap-updated-with-verification-gates.md
    - 16. Technical Specifications: prd/16-technical-specifications.md
    - 17. Non-Functional Requirements: prd/17-non-functional-requirements.md
    - 18. Data Model Overview: prd/18-data-model-overview.md
    - 19. Integration Specifications: prd/19-integration-specifications.md
    - 20. Deployment & Operations: prd/20-deployment-operations.md
    - 21. Success Criteria: prd/21-success-criteria.md
    - 22. Risk Assessment & Mitigation: prd/22-risk-assessment-mitigation.md
    - 23. Acceptance Criteria Summary: prd/23-acceptance-criteria-summary.md
    - 24. Spring Modulith Architecture Compliance Summary: prd/24-spring-modulith-architecture-compliance-summary.md
    - 25. Non‑Functional Sizing Appendix: prd/25-non-functional-sizing-appendix.md
    - 26. DB Schema Delta: prd/26-db-schema-delta-additions-changes.md
    - 27. Architecture Decision Records: prd/27-architecture-decision-records-adr.md
  - Event Catalog: event-catalog.md
  - Architecture:
    - System Context: architecture/system-context.md
    - Module Architecture: architecture/module-architecture.md
    - Deployment Architecture: architecture/deployment-architecture.md
    - Data Architecture: architecture/data-architecture.md
    - Data Access (MyBatis‑Plus): architecture/data-access-mybatis-plus.md
    - Eventing Architecture: architecture/eventing-architecture.md
    - Security Architecture: architecture/security-architecture.md
    - Observability & Reliability: architecture/observability-reliability.md
    - Testing Architecture: architecture/testing-architecture.md
    - API Architecture: architecture/api-architecture.md
    - Gateway (Envoy): architecture/gateway-envoy.md
    - Migrations: architecture/migrations.md
    - Coding Standards: architecture/coding-standards.md
    - Source Tree & Layout: architecture/source-tree.md
  - API Reference:
    - Overview: api/README.md
    - Swagger UI: api/swagger.md
    - OpenAPI (YAML): api/openapi.yaml
    - Modules:
      - Shared Components: api/modules/shared.yaml
      - Incidents: api/modules/incidents.yaml
      - Problems & Known Errors: api/modules/problems.yaml
      - Changes: api/modules/changes.yaml
      - Service Requests: api/modules/service-requests.yaml
      - Knowledge: api/modules/knowledge.yaml
      - Users: api/modules/users.yaml
      - Teams: api/modules/teams.yaml
      - CMDB: api/modules/cmdb.yaml
      - Search: api/modules/search.yaml
      - Events & Webhooks: api/modules/events.yaml
      - System: api/modules/system.yaml
  - UX:
    - UX Overview: ux/README.md
  - ADRs:
    - 0010 Adopt Envoy Gateway (K8s Gateway API): adrs/0010-envoy-gateway-adoption-k8s-gateway-api.md
    - Overview: adrs/README.md
    - 0001 Event-Only Inter-Module Communication: adrs/0001-event-only-inter-module-communication.md
    - 0002 Only 'user' as Shared Module: adrs/0002-user-as-only-shared-foundation-module.md
    - 0003 HA Posture – Single DC: adrs/0003-ha-posture-single-dc-rack-ha.md
    - 0004 Event Contract Versioning: adrs/0004-event-contract-versioning.md
    - 0005 CMDB Impact Assessment Handshake: adrs/0005-cmdb-impact-assessment-handshake.md
    - 0006 Event Publication Partitioning: adrs/0006-event-publication-partitioning-retention.md
    - 0007 API Gateway Placement: adrs/0007-api-gateway-placement-scope.md
    - 0008 Mobile Push Egress: adrs/0008-mobile-push-egress-policy.md
    - 0009 DB Migration Policy: adrs/0009-db-migration-schema-evolution.md
