apiVersion: gateway.envoyproxy.io/v1alpha1
kind: RateLimitPolicy
metadata:
  name: auth-per-token
  namespace: edge
  labels:
    app.kubernetes.io/part-of: synergyflow
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: api-protected
  limits:
    - name: per-token-auth
      rates:
        - requests: ${GATEWAY_RATE_LIMIT_PER_TOKEN:-60}
          unit: minute
      conditions:
        - key: header
          name: x-auth-sub
      match:
        - path:
            type: PathPrefix
            value: /api/auth/

