[versions]
spring-boot = "3.5.6"
spring-depMgmt = "1.1.7"
spring-modulith = "1.4.3"
testcontainers = "1.21.3"
lombok = "1.18.42"
mapstruct = "1.6.3"
junit = "5.10.3"
jacoco = "0.8.12"
mybatis-plus = "3.5.9"

