name: Docs Validation

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions pyyaml mkdocs-swagger-ui-tag

      - name: Generate Aggregated OpenAPI
        run: |
          python scripts/build_openapi.py

      - name: Build MkDocs (strict)
        run: mkdocs build --strict

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Markdownlint
        run: |
          npm install -g markdownlint-cli@0.39.0
          markdownlint "docs/**/*.md"

      - name: Link Check (Lychee)
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --accept 200,429,999 docs/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
